config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get 'home/help', to: "home#help"
  get 'search', to: "home#search", as: "search"
  get 'home/contact', to: "home#contact"
  resources :users, only: %w( edit update show ) do
    collection do
      get :faculty_select
      get :department_select
      get :sold_list
      get :bought_list
      get :contract_list
      get :hope_list
    end
  end
  resources :courses, only: %w{ show index } do
    collection do
      get 'search'
    end
  end
  resources :textbooks, only: %w( new create), shallow: true do
    resources :items, except: %w( index destroy) do
      member do
        resource :item_comments, only: :create
        resource :contract, only: %w( create show update )
      end
    end
  end
  resource :message, only: %w( create )

  namespace :admin do
    resources :users, :except => [:show]
    resources :schools
    resources :faculties
    resources :departments
    resources :courses
    resources :textbooks
    resources :items
  end
  get '/admin' => "admin#index"
  root 'home#index'
  match "/auth/:provider/callback" => "sessions#user_sign_in_up", :via => [:get, :post]
end

app/views/admin/index.html.erb
<div class="collection">
  <%= link_to "users", admin_users_path ,class:"collection-item" %>
  <%= link_to "schools", admin_schools_path ,class:"collection-item" %>
  <%= link_to "faculties", admin_faculties_path ,class:"collection-item" %>
  <%= link_to "departments", admin_departments_path ,class:"collection-item" %>
  <%= link_to "courses", admin_courses_path ,class:"collection-item" %>
  <%= link_to "textbooks", admin_textbooks_path ,class:"collection-item" %>
  <%= link_to "items", admin_items_path ,class:"collection-item" %>
</div>
<!-- <img src="https://books.google.co.jp/books/content?id=zhXVPAAACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE73zIFRsEkN63lwxTSuIA4peSwQkwplA0etoVpT5Q7TY7vi_oCNSkhH1U-kjx1MtXyFDDKmf3Tk8t2WZBfD90OcRlIHKlXsKvpGzImy6loP4Wkqf7e11C5pkFSjD3j9ygrqbxXyD"> -->