config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get 'home/help', to: "home#help"
  get 'search', to: "home#search", as: "search"
  get 'home/contact', to: "home#contact"
  resources :users, only: %w( edit update show ) do
    collection do
      get :faculty_select
      get :department_select
      get :sold_list
      get :bought_list
      get :contract_list
      get :hope_list
    end
  end
  resources :courses, only: %w{ show index } do
    collection do
      get 'search'
    end
  end
  resources :textbooks, only: %w( new create), shallow: true do
    resources :items, except: %w( index destroy) do
      member do
        resource :item_comments, only: :create
        resource :contract, only: %w( create show update )
      end
    end
  end
  resource :message, only: %w( create )

  namespace :admin do
    resources :users, :except => [:show]
    resources :schools
    resources :faculties
    resources :departments
    resources :courses
    resources :textbooks
    resources :items
  end
  get '/admin' => "admin#index"
  root 'home#index'
  match "/auth/:provider/callback" => "sessions#user_sign_in_up", :via => [:get, :post]
end

app/views/shared/_home.html.erb
<div>
  <input id="search_course_field2" type="text" class="validate" placeholder="出品/購入も授業名で検索">
  <label for="search_course_field2"></label>
</div>
<div id="course_result2">
</div>
<% unless user_signed_in? %>
  <div class="valign center Home__login_btn">
    <div id="social-icon"class="clear">
      <%= link_to user_google_oauth2_omniauth_authorize_path do %>
        <i class="fa fa-google fa-lg"></i>大学メールでログイン
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_item_show_private.html.erb
<% if item.seller_id == current_user.id %>
  <% if item.purchased == false %>
    <%= link_to edit_item_path(item), class:"btn waves-effect waves-light item--btn", data:{disable_with: "通信中"} do%>
    　　編集する
    <% end %>
  <% else %>
    <%= link_to contract_path(item.contract) do %>
      <p class="btn waves-effect grey waves-light">やり取り</p>
    <% end %>
  <% end %>
<% else %>
  <% if item.purchased == false %>
    <% if item.published == true %>
      <%= link_to contract_path, method: :post, class:"btn waves-effect waves-light #{item_type[0]} item--btn", data:{confirm: "#{@item_type[1]}しますか？", disable_with: "通信中"} do%>
      　<%= item_type[1] %>
        <i class="material-icons right">send</i>
      <% end %>
    <% else %>
    　<p class="btn waves-effect grey waves-light">非公開</p>
    <% end %>
  <% else %>
    <p class="btn waves-effect grey waves-light">購入済み</p>
  <% end %>
<% end %>

app/views/shared/_item_show_public.html.erb
<% if user_signed_in?%>
  <% if item.purchased == false %>
    <%= link_to contract_path, method: :post, class:"btn waves-effect waves-light #{item_type[0]}", data:{confirm: "#{@item_type}しますか？", disable_with: "通信中"} do%>
    　<%= item_type[1] %>
      <i class="material-icons right">send</i>
    <% end %>
  <% else %>
    <p class="btn waves-effect grey waves-light">購入済み</p>
  <% end %>
<% else %>
  <div class="btn user_unlogin <%= item_type[0] %>"><%= @item_type[1] %>します</div>
  <div id="user_modal" class="modal">
    <div class="modal_close-u"><i class="material-icons">close</i></div>
    <div class="modal-content">
      <h4><%= @item_type[1] %>するためには</br>ログイン/会員登録が必要です。
      </h4>
      <div class="img">
        <%= image_tag('icon.jpg', { size: "200x200", alt: 'アイコン'}) %>
      </div>
    </div>
    <div class="valign center Home__login_btn">
      <div id="social-icon"class="clear">
        <%= link_to user_google_oauth2_omniauth_authorize_path do %>
          <i class="fa fa-google fa-lg"></i>大学メールでログイン
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_many_text_items.html.erb
<% courses.each do |course| %>
  <% course.textbooks.each do |text_book| %>
    <div clss="row">
      <div class="col s6 m12 l<%= size %> Course__show__item_show <% if size == 6 %><% end %> hoverable">
        <div class="course__show">
          <h6 class="truncate"><%= course.faculty.name %>/<% if course.period_i18n == "その他" %>その他<% else %><%= course.day_i18n[0] %><%= course.period_i18n[0] %><% end %>
          </h6>
          <p class="truncate amber-text text-darken-1 cource__name"><%= course.name %>　　
            <span class="right-align"></span>
          </p>
          <p class="truncate cource__name"><%= text_book.name %></p>
          <hr>
          <div class="row">
            <div class="col s12 m3 l12 Course__show__item_show--img">
              <thead></thead>
              <div class="row">
                <div class="col m12 l3 s12">
                  <div class="center-align">
                    <%= image_tag("#{text_book.thumbnail == "none" ? "no_img.png" : text_book.thumbnail }", class: "text-img-#{size}") %>
                  </div>
                </div>
                <div class="col m12 l6 hide-on-small-only">
                    <%= link_to "出品", new_textbook_item_path(text_book.id, item_type: 0), class:"waves-effect waves-light btn bbtn" %>
                    <%= link_to "求む", new_textbook_item_path(text_book.id, item_type: 1), class:"waves-effect waves-light btn amber bbtn"%>
                    <%= link_to "詳細", course_path(course.id), class:"waves-effect waves-light btn bbtn white blue-text text-darken-2" %>
                    <% if course.items.count == 0 %>
                      <p class="right">未出品</p>
                    <% else %>
                      <%= link_to "#{course.items.count}出品", course_path(course.id), class:"blue-text text-darken-2 right" %>
                    <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="row hide-on-med-and-up">
            <div class="col s12 hide-on-med-and-up">
                <%= link_to "出品", new_textbook_item_path(text_book.id, item_type: 0), class:"waves-effect waves-light btn bbtn" %>
                <%= link_to "求む", new_textbook_item_path(text_book.id, item_type: 1), class:"waves-effect waves-light btn amber bbtn"%>
                <%= link_to "詳細", course_path(course.id), class:"waves-effect waves-light btn bbtn white blue-text text-darken-2" %>
                <% if course.items.count == 0 %>
                  <p class="right">未出品</p>
                <% else %>
                  <p class="blue-text text-darken-2 right"><%= course.items.count %>出品</p>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_show_item.html.erb
<div clss="row">
  <div class="col s12 m12 l12 Course__show__item_show">
    <div class="Course__show">
      <h6 class="truncate"><%= course.faculty.name %>/<%= course.day_i18n %>/<%= course.period_i18n %>
      </h6>
      <h4 class="truncate amber-text text-darken-1 Course__show__item_show__name"><%= course.name %></h4>
      <hr>
      <div class="row">
        <div class="col s12 m3 l3 Course__show__item_show--img">
          <thead></thead>
          <div class="center">
            <%= image_tag("#{text_book.thumbnail == "none" ? "no_img.png" : text_book.thumbnail }", class: "text-img-#{size}") %>
          </div>
        </div>
        <div class="col s12 m9 l9 Course__show__item_show--description">
          <table class="bordered truncate">
            <thead></thead>
            <tbody>
              <tr>
              <th>出品者</th>
              <td><%= link_to item.sell_user.name, user_path(item.sell_user.id) %></td>
              </tr>
              <tr>
              <th>書籍名</th>
              <td><%= item.textbook.name %></td>
              </tr>
              <tr>
              <th>価格</th>
              <td><%= render partial: "shared/show_price", locals: {item: item} %></td>
              </tr>
              <tr>
              <th>保存状態</th>
              <td><%= item.status_i18n %></td>
              </tr>
              <tr>
              <th>取引方法</th>
              <td><%= item.delivery_i18n %></td>
              </tr>
              <tr>
              <th>備考</th>
              <td><%= item.description %></td>
              </tr>
              <tr>
              <th>公開状態</th>
              <td><%= item.published ? "公開" : "非公開" %></td>
              </tr>
            </tbody>
          </table>
          <div class="right-align">
            <p>by Google Books</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_show_price.html.erb
<% if item.price == 9999 %>
交渉
<% else %>
<%= item.price %>円
<% end %>

app/views/shared/_small_many_text_items.html.erb
<% courses.each do |course| %>
  <% course.textbooks.each do |text_book| %>
    <div clss="row">
      <div class="col s12 m12 l<%= size %> Course__show__item_show <% if size == 6 %><% end %> hoverable">
        <div class="Course__show">
          <h5 class="truncate"><%= course.name %>　　
            <span class="right-align"><i class="material-icons">event_note</i><% if course.period_i18n == "その他" %>その他<% else %><%= course.day_i18n[0] %><%= course.period_i18n[0] %><% end %></span></h5>
          <hr>
          <div class="row">
            <div class="col s12 m3 l3 Course__show__item_show--img">
              <thead></thead>
              <div class="row">
                <div class="col m12 l12 s12">
                  <div class="center-align">
                    <%= image_tag("#{text_book.thumbnail == "none" ? "no_img.png" : text_book.thumbnail }", class: "text-img-#{size}") %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col s6 m12 l12 hide-on-small-only">
                    <%= link_to "出品", new_textbook_item_path(text_book.id, item_type: 0), class:"waves-effect waves-light btn bbtn" %>
                    <%= link_to "求む", new_textbook_item_path(text_book.id, item_type: 1), class:"waves-effect waves-light btn amber bbtn"%>
                </div>
              </div>
            </div>
            <div class="col s12 m9 l9 Course__show__item_show--description">
              <table class="bordered truncate">
                <thead></thead>
                <tbody>
                  <tr>
                  <th>書籍名</th>
                  <td><%= text_book.name %></td>
                  </tr>
                  <tr>
                  <th>著者</th>
                  <td><%= text_book.author %></td>
                  </tr>
                  <tr>
                  <th>詳細</th>
                  <td><%= text_book.explanation %></td>
                  </tr>
                  <!-- <tr> -->
                  <!-- <th>出品平均価格</th> -->
                  <!-- <td>Comming soon!</td> -->
                  <!-- <td><%# items.inject(0){|r, i| r+=i.price}/items.size %>円</td> -->
                  <!-- </tr> -->
                  <tr>
                  <th>Amazon</th>
                  <td><%= link_to "ページに飛ぶ", "https://www.amazon.co.jp/s/ref=sr_nr_n_0?fst=as%3Aoff&keywords=#{text_book.name}+#{text_book.publisher}&ie=UTF8&qid=1491317462&rnid=2321267051", target: ["_blank"]  %></td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div class="row hide-on-med-and-up">
            <div class="col s12 hide-on-med-and-up">
                <%= link_to "出品", new_textbook_item_path(text_book.id, item_type: 0), class:"waves-effect waves-light btn bbtn" %>
                <%= link_to "求む", new_textbook_item_path(text_book.id, item_type: 1), class:"waves-effect waves-light btn amber bbtn"%>
            </div>
          </div>
          <div class="row">
            <div class="col s12 m12 l12 Course__show__item_show--list">
              <div class="col s12">
                <% text_book.items.each do |item| %>
                <div class="collection">
                  <%= link_to item_path(item), class:"collection-item" do %>
                    <%= item.price%>円
                    <%= item_tag(item) %>
                  <% end %>
                </div>
                <% end %>
              </div>
            </div>
             <%= back_link(course) %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_text_items.html.erb
<% course.textbooks.each do |text_book| %>
<div clss="row">
  <div class="col s12 m12 l<%= size %> Course__show__item_show <% if size == 6 %><% end %>">
    <div class="Course__show">
      <h6 class="truncate"><%= course.faculty.name %>/<%= course.day_i18n %>/<%= course.period_i18n %>
      </h6>
      <h4 class="truncate amber-text text-darken-1 Course__show__item_show__name"><%= course.name %></h4>
      <hr>
      <div class="row">
        <div class="col s12 m3 l3 Course__show__item_show--img">
          <thead></thead>
          <div class="center">
            <%= image_tag("#{text_book.thumbnail == "none" ? "no_img.png" : text_book.thumbnail }", class: "text-img-#{size}") %>
          </div>
          <div class="center">
            <%= link_to "出品", new_textbook_item_path(text_book.id, item_type: 0), class:"waves-effect waves-light btn " %>
            <%= link_to "求む", new_textbook_item_path(text_book.id, item_type: 1), class:"waves-effect waves-light btn amber"%>
          </div>
        </div>
        <div class="col s12 m9 l9 Course__show__item_show--description">
          <table class="bordered truncate">
            <thead></thead>
            <tbody>
              <tr>
              <th>書籍名</th>
              <td><%= text_book.name %></td>
              </tr>
              <tr>
              <th>著者</th>
              <td><%= text_book.author %></td>
              </tr>
              <tr>
              <th>詳細</th>
              <td><div class="scroll"><%= text_book.explanation %></div></td>
              </tr>
              <tr>
              <th>Amazon</th>
              <td><%= link_to "ページに飛ぶ", "https://www.amazon.co.jp/s/ref=sr_nr_n_0?fst=as%3Aoff&keywords=#{text_book.name}+#{text_book.publisher}&ie=UTF8&qid=1491317462&rnid=2321267051", target: ["_blank"] %></td>
              </tr>
            </tbody>
          </table>
          <div class="right-align">
            <p>by Google Books</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col s12 m12 l12 Course__show__item_show--list">
          <div class="col s12">
            <% text_book.items.each do |item| %>
            <div class="collection">
              <%= link_to item_path(item), class:"collection-item" do %>
              <%= render partial: "shared/show_price", locals: {item: item} %>
              <%= item_tag(item) %>
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
         <%# back_link(course) %>
         <%= link_to "戻る", :back, class:"back_link waves-effect waves-light btn white blue-text text-darken-2" %>
      </div>
    </div>
  </div>
</div>
<% end %>

<%# if current_page?(controller: "course", action: "index") %>